# Numpy


In [1]:
import numpy as np # import numpy

In [2]:
# syntax of array creation 
# var = np.array([collection])
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
print(type(arr))# check the data type

<class 'numpy.ndarray'>


In [4]:
b = ([1,2,3,4,5])
type(b)

list

In [5]:
a = np.array([1,2,3,"Ankit",2+7j])
type(a[3])
type(a[4])         # string high priority

numpy.str_

In [6]:

a = np.arange(1,15,2)
a

array([ 1,  3,  5,  7,  9, 11, 13])

In [7]:
len(a) # find of lenght

7

In [8]:
#reshape()
# syntax var.reshape(r,c)
a = np.arange(1,51,2)
len(a)


25

In [9]:
a.reshape(5,5)


array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [10]:
# Accesing  the value
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
n1 + n2


array([5, 7, 9])

In [11]:
# shape (check shape)
a = np.array([1,2,34,4])
a.shape


(4,)

In [12]:
# shape
a = np.array([[1,2,34,4],
            [1,2,3,3]])
a.shape


(2, 4)

In [13]:
# shape
a = np.array([[[1,2,34,4],
            [1,2,3,3],
            [2,3,4,5],
            [4,4,3,3]]])
print(a.shape) # or a.shape


(1, 4, 4)


In [14]:
#zero()# it create dummy data
# syntax   np.zeros(shape)
a = np.zeros(4) # 1D array
a 


array([0., 0., 0., 0.])

In [15]:
# syntax    var = np.zeros((r,c))   2D array
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [16]:
# syntrx   var = np.zeros((r,c,n))    #3D array
a = np.zeros((3,3,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
# ndim   it returns the dimension
a = np.array([[1,2,3,4],[1,2,3,4]])
a.ndim

2

In [18]:
a.dtype  # tells the datatype

dtype('int64')

In [19]:
a.shape  # it tell size of array

(2, 4)

In [20]:
a.size  # tells total size

8

In [21]:
#ones()   create array with fill 1
# syntax  var =  np.once()
a = np.ones(5)   # for 1D array
a

array([1., 1., 1., 1., 1.])

In [22]:
a = np.ones((2,3))   # for 2D array
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
# arange()
# syntax     np.array(start,stop,step)

a = np.arange(5)  # simple arange
a

array([0, 1, 2, 3, 4])

In [24]:
a = np.arange(2,10)     # start and end
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a = np.arange(1,20,2)   # with step
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [26]:
a = np.arange(1,2,0.2)   # with step   float
a

array([1. , 1.2, 1.4, 1.6, 1.8])

In [27]:
#eye()  cretae identity diagonal matrix  with 1 and other zero
# syntax    np.ey(n)
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
# syntax       np.random.randint(sv,ev,n)  it will generate random value


In [29]:
a = np.random.randint(1,100,10)
a


array([ 2, 82, 51, 38, 30,  9, 77, 19, 33, 82], dtype=int32)

In [30]:
print(a)

[ 2 82 51 38 30  9 77 19 33 82]


# Indexing and slicing

In [31]:
# indexing    : slecting special elements
# syntax var[index_position]
a = np.arange(111,121)
a



array([111, 112, 113, 114, 115, 116, 117, 118, 119, 120])

In [32]:
a[2]

np.int64(113)

In [38]:
# for 2d array
a = np.array([[5,2,3],[1,2,3]])
a

array([[5, 2, 3],
       [1, 2, 3]])

In [39]:
#a[row,column]
a[0,0]

np.int64(5)

In [41]:
a[1,1]

np.int64(2)

In [42]:
# indexing 3d array
a = np.array([[[1,2,3],[2,3,4],[2,5,5]]])
a

array([[[1, 2, 3],
        [2, 3, 4],
        [2, 5, 5]]])

In [47]:
# a[block,row,column]

print(a[0,1,1])

3


In [55]:
# slicing  - selecting a range (portion) of elements using start index,end index,stepvalue
a = np.arange(11,55)
a
# a = a.reshape(5,5)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50, 51, 52, 53, 54])

In [56]:
len(a)

44

In [60]:
b = np.array([[[1,2,3],[2,3,4],[2,5,5]]])
b

array([[[1, 2, 3],
        [2, 3, 4],
        [2, 5, 5]]])

In [61]:
b[0:2]

array([[[1, 2, 3],
        [2, 3, 4],
        [2, 5, 5]]])

In [62]:
b[0:2,1:3]

array([[[2, 3, 4],
        [2, 5, 5]]])

In [64]:
#total coumn slice
b[:,2]

array([[2, 5, 5]])

In [66]:
# 3d slicing
  # syntax -  array[block slice,row slice,column slice]
a = np.array([
    [[1,2,3],
    [2,3,4]],
    [[6,7,8],
    [9,7,6]]
])
a

array([[[1, 2, 3],
        [2, 3, 4]],

       [[6, 7, 8],
        [9, 7, 6]]])

In [67]:
# slice entire block
a[0]

array([[1, 2, 3],
       [2, 3, 4]])

In [68]:
a[0,:,:]

array([[1, 2, 3],
       [2, 3, 4]])

In [70]:
# slice 1 row from all blocks
a[:,1,:]

array([[2, 3, 4],
       [9, 7, 6]])

In [71]:
# selecting 1 columns from all blocks
a[:,:,1]

array([[2, 3],
       [7, 7]])

In [72]:
# full 3d slicing
a[0:2,0:1,1:3]

array([[[2, 3]],

       [[7, 8]]])

In [74]:
# selecting only one elemnts
a[0,0,1]

np.int64(2)

# Aggregate function

In [90]:
# sum()
a1 =np.arange(1,11)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
a1.sum()

np.int64(55)

In [85]:
# for 2 d array
y = np.arange(2,22)
y

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

In [87]:
y.reshape(4,5)

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21]])

In [89]:
print(y.sum())

230


In [94]:
# mean()
a1.mean()

np.float64(5.5)

In [95]:
y.mean()

np.float64(11.5)

In [96]:
a1.max()

np.int64(10)

In [97]:
y.max()

np.int64(21)

In [99]:
a =np.arange(1,11)
a
np.mean(a)

np.float64(5.5)

#  flatten():

In [100]:
# convert into single dimension
# syntax arr.flaten()
b = np.array([[[1,2,3],[2,3,4],[2,5,5]]])
b

array([[[1, 2, 3],
        [2, 3, 4],
        [2, 5, 5]]])

In [103]:
flat = b.flatten()
print(flat)

[1 2 3 2 3 4 2 5 5]


In [104]:
# ravel()     returns a 1 d view of array

r = b.ravel()
print(r)

[1 2 3 2 3 4 2 5 5]


# joining array


In [106]:
#1) np.concatenate()    # joing array in sequence
a = np.array([1,2,3,4])
b = np.array([5,6,6,5])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6 6 5]


In [109]:
# 2)  np.vstack()   # vertical join (top to bottum)
v = np.vstack((a,b))
print(v)

[[1 2 3 4]
 [5 6 6 5]]


In [110]:
#3) np.hstack()    # horizontal join
h = np.hstack((a,b))
print(h)

[1 2 3 4 5 6 6 5]


In [111]:
# 4)  np.stack()   # new dimension add

s = np.stack((a,b))
print(s)


[[1 2 3 4]
 [5 6 6 5]]


# spliting 

In [112]:
# divide long array into a small array


In [116]:
# 1) np.split()   # split into equal parts
x = np.array([1,2,3,4,5,6,7,8,9,7,5,4,2,2])
s = np.split(x,2)
print(s)

[array([1, 2, 3, 4, 5, 6, 7]), array([8, 9, 7, 5, 4, 2, 2])]


In [122]:
b = np.array([1,2,3,4,5,6,7,8,9,7,5,4,2,2,4])
s = np.split(b,3)
print(s)

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9, 7]), array([5, 4, 2, 2, 4])]


In [139]:
#2) np.vsplit()   # vertical split 

a = np.array([[1,2,3],
              [1,2,3],
              [2,3,4],
              [4,4,3]])

print(np.vsplit(a, 4))

[array([[1, 2, 3]]), array([[1, 2, 3]]), array([[2, 3, 4]]), array([[4, 4, 3]])]


In [141]:
a.shape

(4, 3)

In [143]:
# 3) h.split()  Horizontal split
print(np.hsplit(a,3))

[array([[1],
       [1],
       [2],
       [4]]), array([[2],
       [2],
       [3],
       [4]]), array([[3],
       [3],
       [4],
       [3]])]


# copy()  
 it create a complete new array with new memory dont affect the original array
 

In [144]:
a = np.array([1,2,3])
b = a.copy()
b[0]=121
print(a)
print(b)

[1 2 3]
[121   2   3]


# view()
work same as copy but also change the original

In [145]:
a = np.array([1,2,3])
b = a.view()
b[0]=121
print(a)
print(b)

[121   2   3]
[121   2   3]
